%YAML:1.0
# tapnext related
tapnext_enable: 1
tapnext_onnx_path: "/datasets/tapnext_128.onnx"
tapnext_engine_path: "/datasets/tapnext_128.engine"
tapnext_max_track: 128
tapnext_reset_boundary_ratio_x: 0.3
tapnext_reset_boundary_ratio_y: 1.0
tapnext_reset_min_percent: 0.1
tapnext_reset_min_count: 10
tapnext_reset_max_frames: 25

# loss parameters for optimization
loss_type: 1
loss_parameter: 5.0
loss_type_initial: 0
loss_parameter_initial: 1.0

# netvlad?
netvlad_engine_path: "/datasets/netvlad_final_32.engine"                                                                                                                                   
netvlad: 1                                                                                                                                                                               
netvlad_threshold: 0.5                                                                                                                                                                     
                                                                                                                                                                                           
depth_engine_path: "/datasets/depth_anything_ac_16.engine"
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 

use_depth: 0
min_features: 35
rgd: 1
use_cuda_in_optimization: 0
use_cuda_in_tracking: 0


imu: 1         
num_of_cam: 1  

imu_topic: "/zed/zed_node/imu/data"
image0_topic: "/zed/zed_node/left/color/rect/image"
image1_topic: "/zed/zed_node/right/color/rect/image"
output_path: "/data/zed_output/"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 360

fx: 1058.17447808064
fy: 1058.44701136475
cx: 675.570437960496
cy: 334.660609848669

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-4.24811718e-03,  1.06355930e-03,  9.99990411e-01, -3.45219088e-06,
          -9.99862513e-01,  1.60239856e-02, -4.26461647e-03,  8.42272147e-05,
          -1.60283676e-02, -9.99871042e-01,  9.95341301e-04, -3.62660654e-07,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 256            # max feature number in feature tracking
min_dist: 25            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
